accounts:
  - name: daniel
    coins: ["20000coopcoin","200000000stake"]
  - name: jenson
    coins: ["10000coopcoin"]
  - name: furen
    coins: ["3000coopcoin"]
    
    
validator:
  name: daniel
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: jenson
  coins: ["5coopcooin"]

build:
  binary: "mychaind"
