accounts:
  - name: genesis
    coins: ["1000000000000000stake"]

    
validator:
  name: genesis
  staked: "10000000stake"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: genesis
  coins: ["1000stake"]

build:
  binary: "mychaind"

