accounts:
  - name: user
    coins: ["1000000000000stake"]

    
validator:
  name: user
  staked: "10000000stake"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: user
  coins: ["5coopcooin"]

build:
  binary: "mychaind"
