accounts:
  - name: genesis
    coins: ["1000000000000000utcoin"]
  - name: faucet
    coins: ["1000000utcoin"]
  - name: validator0
    coins: ["1000000000stake"]

    
validator:
  name: validator0
  staked: "10000000stake"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: faucet
  coins: ["10utcoin"]

build:
  binary: "mychaind"
  
genesis:
  app_state:
    staking:
      params:
        bond_denom: "stake"
